import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
    
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
      <div className={styles.section}><div className={styles.titlename}><span className={styles.span}></span></div></div>
      </div>
        <ToastContainer/>
      <section className={styles.sectionbox}>

      <div className={styles.notifibar}>
        <div className={styles.notifibox}>
          <li>
            <a>NEW NOTIFICATIONS </a>
          </li>
        </div>
      </div>

      <div className={styles.boxcontainer}>
        <div className={styles.box}>
          <Link href="./book/form">
            <a>
              <Image
                className={styles.img}
                src="/bookicon.png"
                alt=""
                height={200}
                width={200}
                />
              <div className={styles.content}>
                <h3 className={styles.h3}> Materials</h3>
                <h6 className={styles.p}>
                  Here you can sell/buy/donate your books.
                </h6>
              </div>
            </a>
          </Link>
        </div>
        <div className={styles.box}>
          <Link href="/">
            <a>
              <Image
                className={styles.img}
                src="/gateicon.jpeg"
                alt=""
                height={180}
                width={200}
                />
              <div className={styles.content}>
                <h3 className={styles.h3}> Gate </h3>
                <h6 className={styles.p}>
                  Suggestions & notes form senior students of our college.
                </h6>
              </div>
            </a>
          </Link>
        </div>
        <div className={styles.box}>
          <Link href="/">
            <a>
              <Image
                className={styles.img}
                src="/gateicon.jpeg"
                alt=""
                height={180}
                width={200}
                />
              <div className={styles.content}>
                <h3 className={styles.h3}> Gate </h3>
                <h6 className={styles.p}>
                  Suggestions & notes form senior students of our college.
                </h6>
              </div>
            </a>
          </Link>
        </div>
        <div className={styles.box}>
          <Link href="/">
            <a>
              <Image
                className={styles.img}
                src="/gateicon.jpeg"
                alt=""
                height={180}
                width={200}
                />
              <div className={styles.content}>
                <h3 className={styles.h3}> Gate </h3>
                <h6 className={styles.p}>
                  Suggestions & notes form senior students of our college.
                </h6>
              </div>
            </a>
          </Link>
        </div>
        <div className={styles.box}>
          <Link href="/">
            <a>
              <Image
                className={styles.img}
                src="/gateicon.jpeg"
                alt=""
                height={180}
                width={200}
                />
              <div className={styles.content}>
                <h3 className={styles.h3}> Gate </h3>
                <h6 className={styles.p}>
                  Suggestions & notes form senior students of our college.
                </h6>
              </div>
            </a>
          </Link>
        </div>
        <div className={styles.box}>
          <Link href="/">
            <a>
              <Image
                className={styles.img}
                src="/gateicon.jpeg"
                alt=""
                height={180}
                width={200}
                />
              <div className={styles.content}>
                <h3 className={styles.h3}> Gate </h3>
                <h6 className={styles.p}>
                  Suggestions & notes form senior students of our college.
                </h6>
              </div>
            </a>
          </Link>
        </div>
      </div>
                </section>
    </div>
  );
}
